title: ScienceTo
description: Website showcasing my works
theme: just-the-docs

url: https://scienceto.com

logo: "/assets/images/st-low-resolution-logo-black-on-white-background-128x96-1.png"
favicon_ico: "/assets/images/st-low-resolution-logo-black-on-white-background-128x96-1.ico"

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

ga_tracking: G-LD9FH2JMPR
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)


# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Copyright &copy; Jheel Patel."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html


collections:
  grad:
    permalink: "/:collection/:path"
    output: true
  # undergrad:
  #   permalink: "/:collection/:path"
  #   output: true
  projects:
    permalink: "/:collection/:path"
    output: true
just_the_docs:
  collections:
    grad:
      name: Master's Coursework
      nav_fold: true
      nav_exclude: false
    projects:
      name: Projects
      nav_fold: true
      nav_exclude: false
    # undergrad:
    #   name: Bachelor's Coursework
    #   nav_fold: true
    #   nav_exclude: false

# For copy button on code
enable_copy_code_button: true
